name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{ matrix.tag }} - ${{ matrix.os }} )
    strategy:
      matrix:
        tag:
          - VALGRIND_3_23_0
          - VALGRIND_3_22_0
          - VALGRIND_3_21_0
          - VALGRIND_3_20_0
          - master
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./build.sh ${{ matrix.tag }}

      - name: Artifact Name
        id: artifact_name
        run: |
          set -eo pipefail
          case ${{ matrix.tag }} in
            VALGRIND_*)
              version=$(echo ${{ matrix.tag }} | sed 's/VALGRIND_//' | sed 's/_/./g')
              ;;
            *)
              version="master"
              ;;
          esac
          echo "artifact_name=valgrind-${version}-$(uname -s)-$(uname -m)" >> $GITHUB_OUTPUT

      - name: Create Archive
        run: |
          set -eo pipefail
          mkdir -p upload/
          mv dist ${{ steps.artifact_name.outputs.artifact_name }}
          tar -czvf upload/${{ steps.artifact_name.outputs.artifact_name }}.tar.gz ${{ steps.artifact_name.outputs.artifact_name }}
          rm -rf ${{ steps.artifact_name.outputs.artifact_name }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.artifact_name }}
          path: upload/*

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Move Artifacts
        run: |
          set -eo pipefail
          mkdir -p upload
          find artifacts/ -type f -exec mv {} $(pwd)/upload/ \;
          rm -rf artifacts/

      - uses: ncipollo/release-action@v1
        with:
          artifacts: upload/*
          makeLatest: true
          allowUpdates: true
          name: Auto-Release ${{ github.run_id }}
          body: |
            This is an auto-release of valgrind.
            Triggered by ${{ github.event_name }}
            [View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          tag: latest
          replacesArtifacts: true

      - uses: ncipollo/release-action@v1
        with:
          artifacts: upload/*
          makeLatest: false
          allowUpdates: true
          name: Auto-Release ${{ github.run_id }}
          body: |
            This is an auto-release of valgrind.
            Triggered by ${{ github.event_name }}
            [View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          tag: auto-release-${{ github.run_id }}
          replacesArtifacts: true
