on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        tag:
          - VALGRIND_3_23_0
          - VALGRIND_3_22_0
          - VALGRIND_3_21_0
          - VALGRIND_3_20_0
          - master
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./build.sh ${{ matrix.tag }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: valgrind-${{ matrix.tag }}-${{ matrix.os }}
          path: dist/
